/* eslint-disable prefer-const */
/* eslint-disable no-var */
/* eslint-disable no-prototype-builtins */

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export class Activitie implements IActivitie {
    date!: Date;
    name!: string;

    [key: string]: any;

    constructor(data?: IActivitie) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): Activitie {
        data = typeof data === 'object' ? data : {};
        let result = new Activitie();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["name"] = this.name;
        return data;
    }
}

export interface IActivitie {
    date: Date;
    name: string;

    [key: string]: any;
}

export class Anonymous2 implements IAnonymous2 {
    date!: Date;
    name!: string;

    [key: string]: any;

    constructor(data?: IAnonymous2) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): Anonymous2 {
        data = typeof data === 'object' ? data : {};
        let result = new Anonymous2();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["name"] = this.name;
        return data;
    }
}

export interface IAnonymous2 {
    date: Date;
    name: string;

    [key: string]: any;
}

export class Subcommittee implements ISubcommittee {
    activities!: Anonymous2[];
    name!: string;
    systemCode!: string;
    url!: string;

    [key: string]: any;

    constructor(data?: ISubcommittee) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["activities"])) {
                this.activities = [] as any;
                for (let item of _data["activities"])
                    this.activities!.push(Anonymous2.fromJS(item));
            }
            this.name = _data["name"];
            this.systemCode = _data["systemCode"];
            this.url = _data["url"];
        }
    }

    static fromJS(data: any): Subcommittee {
        data = typeof data === 'object' ? data : {};
        let result = new Subcommittee();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.activities)) {
            data["activities"] = [];
            for (let item of this.activities)
                data["activities"].push(item.toJSON());
        }
        data["name"] = this.name;
        data["systemCode"] = this.systemCode;
        data["url"] = this.url;
        return data;
    }
}

export interface ISubcommittee {
    activities: Anonymous2[];
    name: string;
    systemCode: string;
    url: string;

    [key: string]: any;
}

export class Committee implements ICommittee {
    activities!: Activitie[];
    chamber!: string;
    name!: string;
    subcommittees!: Subcommittee[];
    systemCode!: string;
    type!: string;
    url!: string;

    [key: string]: any;

    constructor(data?: ICommittee) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["activities"])) {
                this.activities = [] as any;
                for (let item of _data["activities"])
                    this.activities!.push(Activitie.fromJS(item));
            }
            this.chamber = _data["chamber"];
            this.name = _data["name"];
            if (Array.isArray(_data["subcommittees"])) {
                this.subcommittees = [] as any;
                for (let item of _data["subcommittees"])
                    this.subcommittees!.push(Subcommittee.fromJS(item));
            }
            this.systemCode = _data["systemCode"];
            this.type = _data["type"];
            this.url = _data["url"];
        }
    }

    static fromJS(data: any): Committee {
        data = typeof data === 'object' ? data : {};
        let result = new Committee();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.activities)) {
            data["activities"] = [];
            for (let item of this.activities)
                data["activities"].push(item.toJSON());
        }
        data["chamber"] = this.chamber;
        data["name"] = this.name;
        if (Array.isArray(this.subcommittees)) {
            data["subcommittees"] = [];
            for (let item of this.subcommittees)
                data["subcommittees"].push(item.toJSON());
        }
        data["systemCode"] = this.systemCode;
        data["type"] = this.type;
        data["url"] = this.url;
        return data;
    }
}

export interface ICommittee {
    activities: Activitie[];
    chamber: string;
    name: string;
    subcommittees: Subcommittee[];
    systemCode: string;
    type: string;
    url: string;

    [key: string]: any;
}

export class Pagination implements IPagination {
    count!: number;

    [key: string]: any;

    constructor(data?: IPagination) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.count = _data["count"];
        }
    }

    static fromJS(data: any): Pagination {
        data = typeof data === 'object' ? data : {};
        let result = new Pagination();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["count"] = this.count;
        return data;
    }
}

export interface IPagination {
    count: number;

    [key: string]: any;
}

export class Request implements IRequest {
    billNumber!: string;
    billType!: string;
    billUrl!: string;
    congress!: string;
    contentType!: string;
    format!: string;

    [key: string]: any;

    constructor(data?: IRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.billNumber = _data["billNumber"];
            this.billType = _data["billType"];
            this.billUrl = _data["billUrl"];
            this.congress = _data["congress"];
            this.contentType = _data["contentType"];
            this.format = _data["format"];
        }
    }

    static fromJS(data: any): Request {
        data = typeof data === 'object' ? data : {};
        let result = new Request();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["billNumber"] = this.billNumber;
        data["billType"] = this.billType;
        data["billUrl"] = this.billUrl;
        data["congress"] = this.congress;
        data["contentType"] = this.contentType;
        data["format"] = this.format;
        return data;
    }
}

export interface IRequest {
    billNumber: string;
    billType: string;
    billUrl: string;
    congress: string;
    contentType: string;
    format: string;

    [key: string]: any;
}

export class BillCommitteesResponse implements IBillCommitteesResponse {
    committees!: Committee[];
    pagination!: Pagination;
    request!: Request;

    [key: string]: any;

    constructor(data?: IBillCommitteesResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["committees"])) {
                this.committees = [] as any;
                for (let item of _data["committees"])
                    this.committees!.push(Committee.fromJS(item));
            }
            this.pagination = _data["pagination"] ? Pagination.fromJS(_data["pagination"]) : <any>undefined;
            this.request = _data["request"] ? Request.fromJS(_data["request"]) : <any>undefined;
        }
    }

    static fromJS(data: any): BillCommitteesResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BillCommitteesResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.committees)) {
            data["committees"] = [];
            for (let item of this.committees)
                data["committees"].push(item.toJSON());
        }
        data["pagination"] = this.pagination ? this.pagination.toJSON() : <any>undefined;
        data["request"] = this.request ? this.request.toJSON() : <any>undefined;
        return data;
    }
}

export interface IBillCommitteesResponse {
    committees: Committee[];
    pagination: Pagination;
    request: Request;

    [key: string]: any;
}
