/* eslint-disable prefer-const */
/* eslint-disable no-var */
/* eslint-disable no-prototype-builtins */

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export class Pagination implements IPagination {
    count!: number | undefined;

    [key: string]: any;

    constructor(data?: IPagination) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.count = _data["count"];
        }
    }

    static fromJS(data: any): Pagination {
        data = typeof data === 'object' ? data : {};
        let result = new Pagination();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["count"] = this.count;
        return data;
    }
}

export interface IPagination {
    count: number | undefined;

    [key: string]: any;
}

export class Request implements IRequest {
    congress!: string | undefined;
    contentType!: string | undefined;
    format!: string | undefined;

    [key: string]: any;

    constructor(data?: IRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.congress = _data["congress"];
            this.contentType = _data["contentType"];
            this.format = _data["format"];
        }
    }

    static fromJS(data: any): Request {
        data = typeof data === 'object' ? data : {};
        let result = new Request();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["congress"] = this.congress;
        data["contentType"] = this.contentType;
        data["format"] = this.format;
        return data;
    }
}

export interface IRequest {
    congress: string | undefined;
    contentType: string | undefined;
    format: string | undefined;

    [key: string]: any;
}

export class Summarie implements ISummarie {
    actionDate!: Date | undefined;
    actionDesc!: string | undefined;
    bill!: Bill | undefined;
    currentChamber!: string | undefined;
    currentChamberCode!: string | undefined;
    lastSummaryUpdateDate!: Date | undefined;
    text!: string | undefined;
    updateDate!: Date | undefined;
    versionCode!: string | undefined;

    [key: string]: any;

    constructor(data?: ISummarie) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.actionDate = _data["actionDate"] ? new Date(_data["actionDate"].toString()) : <any>undefined;
            this.actionDesc = _data["actionDesc"];
            this.bill = _data["bill"] ? Bill.fromJS(_data["bill"]) : <any>undefined;
            this.currentChamber = _data["currentChamber"];
            this.currentChamberCode = _data["currentChamberCode"];
            this.lastSummaryUpdateDate = _data["lastSummaryUpdateDate"] ? new Date(_data["lastSummaryUpdateDate"].toString()) : <any>undefined;
            this.text = _data["text"];
            this.updateDate = _data["updateDate"] ? new Date(_data["updateDate"].toString()) : <any>undefined;
            this.versionCode = _data["versionCode"];
        }
    }

    static fromJS(data: any): Summarie {
        data = typeof data === 'object' ? data : {};
        let result = new Summarie();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["actionDate"] = this.actionDate ? this.actionDate.toISOString() : <any>undefined;
        data["actionDesc"] = this.actionDesc;
        data["bill"] = this.bill ? this.bill.toJSON() : <any>undefined;
        data["currentChamber"] = this.currentChamber;
        data["currentChamberCode"] = this.currentChamberCode;
        data["lastSummaryUpdateDate"] = this.lastSummaryUpdateDate ? this.lastSummaryUpdateDate.toISOString() : <any>undefined;
        data["text"] = this.text;
        data["updateDate"] = this.updateDate ? this.updateDate.toISOString() : <any>undefined;
        data["versionCode"] = this.versionCode;
        return data;
    }
}

export interface ISummarie {
    actionDate: Date | undefined;
    actionDesc: string | undefined;
    bill: Bill | undefined;
    currentChamber: string | undefined;
    currentChamberCode: string | undefined;
    lastSummaryUpdateDate: Date | undefined;
    text: string | undefined;
    updateDate: Date | undefined;
    versionCode: string | undefined;

    [key: string]: any;
}

export class Bill implements IBill {
    congress!: number | undefined;
    number!: string | undefined;
    originChamber!: string | undefined;
    originChamberCode!: string | undefined;
    title!: string | undefined;
    type!: string | undefined;
    updateDateIncludingText!: Date | undefined;
    url!: string | undefined;

    [key: string]: any;

    constructor(data?: IBill) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.congress = _data["congress"];
            this.number = _data["number"];
            this.originChamber = _data["originChamber"];
            this.originChamberCode = _data["originChamberCode"];
            this.title = _data["title"];
            this.type = _data["type"];
            this.updateDateIncludingText = _data["updateDateIncludingText"] ? new Date(_data["updateDateIncludingText"].toString()) : <any>undefined;
            this.url = _data["url"];
        }
    }

    static fromJS(data: any): Bill {
        data = typeof data === 'object' ? data : {};
        let result = new Bill();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["congress"] = this.congress;
        data["number"] = this.number;
        data["originChamber"] = this.originChamber;
        data["originChamberCode"] = this.originChamberCode;
        data["title"] = this.title;
        data["type"] = this.type;
        data["updateDateIncludingText"] = this.updateDateIncludingText ? this.updateDateIncludingText.toISOString() : <any>undefined;
        data["url"] = this.url;
        return data;
    }
}

export interface IBill {
    congress: number | undefined;
    number: string | undefined;
    originChamber: string | undefined;
    originChamberCode: string | undefined;
    title: string | undefined;
    type: string | undefined;
    updateDateIncludingText: Date | undefined;
    url: string | undefined;

    [key: string]: any;
}

export class BillSummariesByCongressResponse implements IBillSummariesByCongressResponse {
    pagination!: Pagination | undefined;
    request!: Request | undefined;
    summaries!: Summarie[] | undefined;

    [key: string]: any;

    constructor(data?: IBillSummariesByCongressResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.pagination = _data["pagination"] ? Pagination.fromJS(_data["pagination"]) : <any>undefined;
            this.request = _data["request"] ? Request.fromJS(_data["request"]) : <any>undefined;
            if (Array.isArray(_data["summaries"])) {
                this.summaries = [] as any;
                for (let item of _data["summaries"])
                    this.summaries!.push(Summarie.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BillSummariesByCongressResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BillSummariesByCongressResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["pagination"] = this.pagination ? this.pagination.toJSON() : <any>undefined;
        data["request"] = this.request ? this.request.toJSON() : <any>undefined;
        if (Array.isArray(this.summaries)) {
            data["summaries"] = [];
            for (let item of this.summaries)
                data["summaries"].push(item.toJSON());
        }
        return data;
    }
}

export interface IBillSummariesByCongressResponse {
    pagination: Pagination | undefined;
    request: Request | undefined;
    summaries: Summarie[] | undefined;

    [key: string]: any;
}