/* eslint-disable prefer-const */
/* eslint-disable no-var */
/* eslint-disable no-prototype-builtins */

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export class Nomination implements INomination {
    citation!: string | undefined;
    congress!: number | undefined;
    description!: string | undefined;
    latestAction!: LatestAction | undefined;
    nominationType!: NominationType | undefined;
    number!: number | undefined;
    organization!: string | undefined;
    partNumber!: string | undefined;
    receivedDate!: Date | undefined;
    updateDate!: Date | undefined;
    url!: string | undefined;

    [key: string]: any;

    constructor(data?: INomination) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.citation = _data["citation"];
            this.congress = _data["congress"];
            this.description = _data["description"];
            this.latestAction = _data["latestAction"] ? LatestAction.fromJS(_data["latestAction"]) : <any>undefined;
            this.nominationType = _data["nominationType"] ? NominationType.fromJS(_data["nominationType"]) : <any>undefined;
            this.number = _data["number"];
            this.organization = _data["organization"];
            this.partNumber = _data["partNumber"];
            this.receivedDate = _data["receivedDate"] ? new Date(_data["receivedDate"].toString()) : <any>undefined;
            this.updateDate = _data["updateDate"] ? new Date(_data["updateDate"].toString()) : <any>undefined;
            this.url = _data["url"];
        }
    }

    static fromJS(data: any): Nomination {
        data = typeof data === 'object' ? data : {};
        let result = new Nomination();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["citation"] = this.citation;
        data["congress"] = this.congress;
        data["description"] = this.description;
        data["latestAction"] = this.latestAction ? this.latestAction.toJSON() : <any>undefined;
        data["nominationType"] = this.nominationType ? this.nominationType.toJSON() : <any>undefined;
        data["number"] = this.number;
        data["organization"] = this.organization;
        data["partNumber"] = this.partNumber;
        data["receivedDate"] = this.receivedDate ? this.receivedDate.toISOString() : <any>undefined;
        data["updateDate"] = this.updateDate ? this.updateDate.toISOString() : <any>undefined;
        data["url"] = this.url;
        return data;
    }
}

export interface INomination {
    citation: string | undefined;
    congress: number | undefined;
    description: string | undefined;
    latestAction: LatestAction | undefined;
    nominationType: NominationType | undefined;
    number: number | undefined;
    organization: string | undefined;
    partNumber: string | undefined;
    receivedDate: Date | undefined;
    updateDate: Date | undefined;
    url: string | undefined;

    [key: string]: any;
}

export class LatestAction implements ILatestAction {
    actionDate!: Date | undefined;
    text!: string | undefined;

    [key: string]: any;

    constructor(data?: ILatestAction) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.actionDate = _data["actionDate"] ? new Date(_data["actionDate"].toString()) : <any>undefined;
            this.text = _data["text"];
        }
    }

    static fromJS(data: any): LatestAction {
        data = typeof data === 'object' ? data : {};
        let result = new LatestAction();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["actionDate"] = this.actionDate ? this.actionDate.toISOString() : <any>undefined;
        data["text"] = this.text;
        return data;
    }
}

export interface ILatestAction {
    actionDate: Date | undefined;
    text: string | undefined;

    [key: string]: any;
}

export class NominationType implements INominationType {
    isCivilian!: boolean | undefined;
    isMilitary!: boolean | undefined;

    [key: string]: any;

    constructor(data?: INominationType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.isCivilian = _data["isCivilian"];
            this.isMilitary = _data["isMilitary"];
        }
    }

    static fromJS(data: any): NominationType {
        data = typeof data === 'object' ? data : {};
        let result = new NominationType();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["isCivilian"] = this.isCivilian;
        data["isMilitary"] = this.isMilitary;
        return data;
    }
}

export interface INominationType {
    isCivilian: boolean | undefined;
    isMilitary: boolean | undefined;

    [key: string]: any;
}

export class Pagination implements IPagination {
    count!: number | undefined;
    next!: string | undefined;

    [key: string]: any;

    constructor(data?: IPagination) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.count = _data["count"];
            this.next = _data["next"];
        }
    }

    static fromJS(data: any): Pagination {
        data = typeof data === 'object' ? data : {};
        let result = new Pagination();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["count"] = this.count;
        data["next"] = this.next;
        return data;
    }
}

export interface IPagination {
    count: number | undefined;
    next: string | undefined;

    [key: string]: any;
}

export class Request implements IRequest {
    congress!: string | undefined;
    contentType!: string | undefined;
    format!: string | undefined;

    [key: string]: any;

    constructor(data?: IRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.congress = _data["congress"];
            this.contentType = _data["contentType"];
            this.format = _data["format"];
        }
    }

    static fromJS(data: any): Request {
        data = typeof data === 'object' ? data : {};
        let result = new Request();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["congress"] = this.congress;
        data["contentType"] = this.contentType;
        data["format"] = this.format;
        return data;
    }
}

export interface IRequest {
    congress: string | undefined;
    contentType: string | undefined;
    format: string | undefined;

    [key: string]: any;
}

export class NominationListByCongressResponse implements INominationListByCongressResponse {
    nominations!: Nomination[] | undefined;
    pagination!: Pagination | undefined;
    request!: Request | undefined;

    [key: string]: any;

    constructor(data?: INominationListByCongressResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["nominations"])) {
                this.nominations = [] as any;
                for (let item of _data["nominations"])
                    this.nominations!.push(Nomination.fromJS(item));
            }
            this.pagination = _data["pagination"] ? Pagination.fromJS(_data["pagination"]) : <any>undefined;
            this.request = _data["request"] ? Request.fromJS(_data["request"]) : <any>undefined;
        }
    }

    static fromJS(data: any): NominationListByCongressResponse {
        data = typeof data === 'object' ? data : {};
        let result = new NominationListByCongressResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.nominations)) {
            data["nominations"] = [];
            for (let item of this.nominations)
                data["nominations"].push(item.toJSON());
        }
        data["pagination"] = this.pagination ? this.pagination.toJSON() : <any>undefined;
        data["request"] = this.request ? this.request.toJSON() : <any>undefined;
        return data;
    }
}

export interface INominationListByCongressResponse {
    nominations: Nomination[] | undefined;
    pagination: Pagination | undefined;
    request: Request | undefined;

    [key: string]: any;
}