<template>
    <v-navigation-drawer
        location="left"
        permanent
        :rail="collapsed"
      >
        <template v-slot:prepend>
          <v-list-item
                lines="two"
                subtitle="Beta"
                title="Generate Code"
                :class="{ 'pl-2': collapsed }"
            >
                <template v-slot:prepend>
                    <v-avatar color="grey-darken-4" class="ml-2">
                        <v-icon color="white" :size="collapsed ? 'xsmall': 'large'">mdi-rocket-launch-outline</v-icon>
                    </v-avatar>
                </template>
            </v-list-item>
        </template>

        <v-divider></v-divider>
        <v-form
            v-if="!collapsed"
            v-model="form"
            @submit.prevent="generateCode"
        >
            <v-list density="compact" nav>
                <v-list-item>
                    <v-text-field v-model="responseName" label="Response Name" hint="Enter name of response" :rules="[rules.required]" persistent-hint></v-text-field>
                </v-list-item>
                <v-list-item>
                    <v-select v-model="language" :items="['C#', 'TypeScript']" hint="Select language" persistent-hint></v-select>
                </v-list-item>
                <v-list-item>
                    <v-text-field v-model="namespace" label="Namespace" hint="Enter the namespace" persistent-hint></v-text-field>
                </v-list-item>
                <v-list-item>
                    <v-textarea v-model="sampleJson" variant="filled" rows="8" hint="Enter sample json" :rules="[rules.required]" persistent-hint></v-textarea>
                </v-list-item>
            </v-list>
            
            <v-btn
                :disabled="!form"
                :loading="loading"
                class="text-uppercase font-weight-medium"
                type="submit"
                variant="text"
                block
                >
                Generate
            </v-btn>
        </v-form>
        <v-btn
            :disabled="!generatedCode"
            class="text-uppercase font-weight-medium"
            type="submit"
            variant="text"
            block
            @click="copyCode"
            >
            <span v-if="!collapsed">Copy</span>
            <v-icon v-else>mdi-content-copy</v-icon>
        </v-btn>

        
        <template v-slot:append>
          <v-list-item
                :class="{ 'pl-2': collapsed }"
            >
                <template v-slot:append>
                    <v-btn
                        :icon="collapsed ? 'mdi-arrow-collapse-right' : 'mdi-arrow-collapse-left'"
                        variant="text"
                        size="small"
                        class="ml-0"
                        @click="collapsed = !collapsed"
                    ></v-btn>
                </template>
            </v-list-item>
        </template>
    </v-navigation-drawer>

    <v-sheet color="grey-lighten-4" style="height: 85vh">
        <div style="overflow: auto; max-height: 80vh">
            <template v-if="loading">
                <v-skeleton-loader color="grey-lighten-4 pa-0" v-for="i in 7" :key="i" type="paragraph">
                </v-skeleton-loader>
            </template>
            <highlightjs
            v-else-if="generatedCode"
            autodetect
            :code="generatedCode"></highlightjs>
            <highlightjs
            v-else
            autodetect
            :code="defaultResponse"></highlightjs>
        </div>
    </v-sheet>
    <v-divider/>
    <v-snackbar
      v-model="snackbar"
    >
      {{ snackbarText }}

      <template v-slot:actions>
        <v-btn
          color="white"
          variant="text"
          @click="snackbar = false"
        >
          Close
        </v-btn>
      </template>
    </v-snackbar>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useDisplay } from 'vuetify';

const { mobile } = useDisplay();
const isMobile = computed(() => mobile.value);




const responseName = ref('MyResponse')
const namespace = ref('MyNamespace')
const language = ref('C#')
const sampleJson = ref(JSON.stringify({ name: 'John Smith', age: 99 }))
const generatedCode = ref('')
const loading = ref(false)
const snackbar = ref(false)
const snackbarText = ref('')
const collapsed = ref(false)
const form = ref(false)
const rules = {
    required: (value: string) => !!value || 'Field is required',
};
const defaultResponse = 
`//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace MyNamespace.MyResponse
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class MyResponse
    {
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("age", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Age { get; set; }
    }
}`

onMounted(() => {
    collapsed.value = isMobile.value
    generateCode()
})

async function generateCode(){
    if(!form.value){
        return;
    }
    
    const codeGenerationRequest = {
        responseName: responseName.value,
        language: language.value,
        namespace: namespace.value,
        sampleJson: sampleJson.value
    }

    loading.value = true
    const response = await fetch('/api/CodeGeneration', {
        method: 'post',
        headers: {
            'Content-Type': 'application/json',
            '___tenant___': 'robsmitha'
        },
        body: JSON.stringify(codeGenerationRequest)
    })

    if(!response.ok){
        loading.value = false
        snackbar.value = true
        snackbarText.value = `An error occurred generating code. Please review sample json for correctness.`
        return
    }

    const data = await response.json()

    loading.value = false
    generatedCode.value = data.code
}

function copyCode(){
    navigator.clipboard.writeText(generatedCode.value)
    snackbar.value = true
    snackbarText.value = `Copied to clipboard`
}

</script>