/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    BillDetails: typeof import('./src/components/Congress/BillDetails.vue')['default']
    BillList: typeof import('./src/components/Congress/BillList.vue')['default']
    CodeGeneration: typeof import('./src/components/Code/CodeGeneration.vue')['default']
    CodeSearch: typeof import('./src/components/Code/CodeSearch.vue')['default']
    CodeSearchCategories: typeof import('./src/components/Code/CodeSearchCategories.vue')['default']
    CodeSearchField: typeof import('./src/components/Code/CodeSearchField.vue')['default']
    CodeSearchRepos: typeof import('./src/components/Code/CodeSearchRepos.vue')['default']
    Commits: typeof import('./src/components/Repo/Commits.vue')['default']
    CongressFeed: typeof import('./src/components/Congress/CongressFeed.vue')['default']
    Devicon: typeof import('./src/components/_helpers/Devicons/Devicon.vue')['default']
    ErrorMessage: typeof import('./src/components/_helpers/ErrorMessage.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    FileContent: typeof import('./src/components/_helpers/FileContent.vue')['default']
    FileContentDialog: typeof import('./src/components/Code/FileContentDialog.vue')['default']
    FileItem: typeof import('./src/components/_helpers/FileItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Languages: typeof import('./src/components/Repo/Languages.vue')['default']
    MyResume: typeof import('./src/components/MyResume.vue')['default']
    OAuthCallback: typeof import('./src/components/OAuthCallback.vue')['default']
    RepoItem: typeof import('./src/components/_helpers/RepoItem.vue')['default']
    Repos: typeof import('./src/components/Home/Repos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starred: typeof import('./src/components/Home/Starred.vue')['default']
    UnDraw: typeof import('./src/components/_helpers/UnDraw/UnDraw.vue')['default']
  }
}
