/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    BillDetails: typeof import('./src/components/Congress/BillDetails.vue')['default']
    BillList: typeof import('./src/components/Congress/BillList.vue')['default']
    CodeGeneration: typeof import('./src/components/Code/CodeGeneration.vue')['default']
    CodeSearch: typeof import('./src/components/Code/CodeSearch.vue')['default']
    CodeSearchCategories: typeof import('./src/components/Code/CodeSearchCategories.vue')['default']
    CodeSearchField: typeof import('./src/components/Code/CodeSearchField.vue')['default']
    CodeSearchRepos: typeof import('./src/components/Code/CodeSearchRepos.vue')['default']
    Devicon: typeof import('./src/components/Code/Devicon.vue')['default']
    FileContentDialog: typeof import('./src/components/Code/FileContentDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyResume: typeof import('./src/components/MyResume.vue')['default']
    OAuthCallback: typeof import('./src/components/OAuthCallback.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
