/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    AccountList: typeof import('./src/components/Financial/AccountList.vue')['default']
    BillDetails: typeof import('./src/components/Congress/BillDetails.vue')['default']
    BillList: typeof import('./src/components/Congress/BillList.vue')['default']
    BudgetAccounts: typeof import('./src/components/Financial/BudgetAccounts.vue')['default']
    Budgets: typeof import('./src/components/Financial/Budgets.vue')['default']
    CodeGeneration: typeof import('./src/components/Code/CodeGeneration.vue')['default']
    CodeSearch: typeof import('./src/components/Code/CodeSearch.vue')['default']
    CodeSearchRepos: typeof import('./src/components/Code/CodeSearchRepos.vue')['default']
    Commits: typeof import('./src/components/Repo/Commits.vue')['default']
    CongressFeed: typeof import('./src/components/Congress/CongressFeed.vue')['default']
    ContentHeader: typeof import('./src/components/Financial/ContentHeader.vue')['default']
    Devicon: typeof import('./src/components/_helpers/Devicons/Devicon.vue')['default']
    EditBudget: typeof import('./src/components/Financial/EditBudget.vue')['default']
    ErrorMessage: typeof import('./src/components/_helpers/ErrorMessage.vue')['default']
    ExcludedTransactions: typeof import('./src/components/Financial/ExcludedTransactions.vue')['default']
    Exemptions: typeof import('./src/components/Financial/Exemptions.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    FileContent: typeof import('./src/components/_helpers/FileContent.vue')['default']
    FileContentDialog: typeof import('./src/components/Code/FileContentDialog.vue')['default']
    FindProduct: typeof import('./src/components/Merchant/FindProduct.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Languages: typeof import('./src/components/Repo/Languages.vue')['default']
    LinkedAccounts: typeof import('./src/components/Financial/LinkedAccounts.vue')['default']
    MyResume: typeof import('./src/components/MyResume.vue')['default']
    OAuthCallback: typeof import('./src/components/OAuthCallback.vue')['default']
    ProductList: typeof import('./src/components/Merchant/ProductList.vue')['default']
    RepoItem: typeof import('./src/components/_helpers/RepoItem.vue')['default']
    Repos: typeof import('./src/components/Home/Repos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveBudgetDialog: typeof import('./src/components/Financial/SaveBudgetDialog.vue')['default']
    SaveEstimateDialog: typeof import('./src/components/Financial/SaveEstimateDialog.vue')['default']
    SaveProductDialog: typeof import('./src/components/Merchant/SaveProductDialog.vue')['default']
    SearchCategories: typeof import('./src/components/_helpers/SearchCategories.vue')['default']
    SearchField: typeof import('./src/components/_helpers/SearchField.vue')['default']
    SearchResultsDialog: typeof import('./src/components/_helpers/SearchResultsDialog.vue')['default']
    Starred: typeof import('./src/components/Home/Starred.vue')['default']
    TrackExpenses: typeof import('./src/components/Financial/TrackExpenses.vue')['default']
    Transactions: typeof import('./src/components/Financial/Transactions.vue')['default']
    UnDraw: typeof import('./src/components/_helpers/UnDraw/UnDraw.vue')['default']
    UserList: typeof import('./src/components/Merchant/UserList.vue')['default']
    ViewProduct: typeof import('./src/components/Merchant/ViewProduct.vue')['default']
  }
}
